#!/bin/perl


use strict;
use warnings;
use File::Basename;
use LWP::Simple;
use JSON;
use Data::Dumper;

if($#ARGV != 1) {
	die "Usage: ", basename($0), " <board> <thread url>\n";
}

my $board   = $ARGV[0];
my $thread  = $ARGV[1];

my $page = get("http://a.4cdn.org/${board}/thread/${thread}.json") or die "Couldn't reach host (or invalid URL)!";

my $dir = "${board}:${thread}";
mkdir($dir);
chdir($dir) or die "$!";

my @posts = @{(from_json($page))->{'posts'}};

my $currentFile = undef;
$SIG{'INT'} = sub {
	print "\n";
	if(defined $currentFile) {
		print "Removing partially downloaded file: ", $currentFile, "\n";
		unlink($currentFile);
	}
	print "... Exiting\n";
	exit 0;
};

my $i = 1;
my $n = (scalar @posts) + 1;
foreach(@posts) {
    my $tim     = $_->{'tim'};
    my $ext     = $_->{'ext'};
    my $fname   = $_->{'filename'};
    unless(defined $tim and defined $ext and defined $fname) {
        print "(", $i++, "/", $n, ") [no file posted]\n";
        next;
    }
    my $url     = "http://i.4cdn.org/${board}/${tim}${ext}";
    my $file    = sprintf("%03d - %s%s", $i, $fname, $ext);
	print "(", $i++, "/", $n, ") ", $file, "\n";
    $currentFile = $file;
    getstore($url, $file);
    $currentFile = undef;
}
