#!/bin/bash

if [[ -z $1 ]]; then
	echo "Usage: imgur-album <album id>"
	exit 1
fi

. $(dirname $0)/imgur-auth.sh

album=$1
mkdir $album
cd $album

response=$(curl -s -H "Authorization: Bearer $access_token" https://api.imgur.com/3/album/$1)
links=$(echo "$response" | grep -o "link\":\"http:\\\/\\\/i\.imgur[^\"]*" | awk -F'"' '{print $3}' | sed 's/\\//g')
if [[ $* == *--print* ]]; then
	echo "$links"
else
	i=1
	IFS=$\n
	n=$(echo $links | wc -l)
	unset IFS
	nd=${#n}
	for link in $links; do
		echo -en "\r"$i/$n
		extension=$(echo $link | grep -o "[^\.]*$")
		[[ $? ]] || {
			extension="jpg"
			echo "failed to get extension"
		}
		echo $extension | grep "/"
		[[ $? ]] || {
			extension="jpg"
			echo "failed to get extension"
		}
        file=$(printf "%0${nd}d" $i)\.$extension
        [[ -e $file ]] || curl -Ss $link > $file
		((i++))
	done
	echo
fi
