#!/bin/perl

use strict;
use warnings;
use utf8;

use File::Basename;
use LWP::Simple;
use HTML::TreeBuilder;
use HTML::Element;
use XML::FeedPP;
use Term::ReadKey;
use Date::Parse;
use Time::Format qw(time_strftime);

if($#ARGV != 0) {
	die "Usage: ", basename($0), " <username>\n";
}

print "Press q to exit\n";

my $user = $ARGV[0];
my $dir = "reddit:" . $user;
mkdir($dir);
chdir($dir) or die $!;
my $url = "http://reddit.com/user/" . $user . "/submitted/.rss";
my $last_after = "";
my $after = "";
my $currentFile;

ReadMode 3;
my $exit = 0;

my $page = $url;
until($exit) {
    $page = XML::FeedPP->new($page) or die "Couldn't reach host (or invalid URL)!";
    
    foreach($page->get_item()) {
        my $key = ReadKey(-1);
        if(defined $key && $key eq 'q') {
            $exit = 1;
            last;
        }

        if($_->link =~ /comments\/([^\/]*)/i) {
            $after = $1;
        }

        my $time = str2time($_->pubDate);
        my $title = time_strftime('%Y-%m-%d %T', $time) . " " . $_->title;
        my $desc = HTML::TreeBuilder->new();
        $desc->parse($_->description);
        $desc->eof;
        my ($link) = $desc->look_down(sub {
            $_[0]->as_text eq "[link]";
        });
        print 'getimage', ' ', $link->attr('href'), ' ', $title, "\n";
        system 'getimage', $link->attr('href'), $title;
        
        $desc->delete;
    }

    if($after eq $last_after) {
        last;
    }
    $page = $url . "?after=t3_" . $after;
    $last_after = $after;
}

ReadMode 0;

exit 0;
