#!/bin/perl


use strict;
use warnings;
use File::Basename;
use LWP::Simple;
use HTML::TreeBuilder;
use HTML::Element;
use XML::FeedPP;
use Term::ReadKey;

if($#ARGV != 0) {
	die "Usage: ", basename($0), " <username>\n";
}

print "Press q to exit\n";

my $user = $ARGV[0];
my $dir = "reddit:" . $user;
mkdir($dir);
chdir($dir) or die $!;
my $url = "http://reddit.com/user/" . $user . "/submitted/.rss";
my $last_after = "";
my $after = "";
my $currentFile;

ReadMode 3;
my $exit = 0;

my $page = $url;
until($exit) {
    $page = XML::FeedPP->new($page) or die "Couldn't reach host (or invalid URL)!";
    
    foreach($page->get_item()) {
        my $key = ReadKey(-1);
        if(defined $key && $key eq 'q') {
            $exit = 1;
            last;
        }

        if($_->link =~ /comments\/([^\/]*)/i) {
            $after = $1;
        }
        my $desc = HTML::TreeBuilder->new();
        $desc->parse($_->description);
        $desc->eof;
        my ($link) = $desc->look_down(sub {
            $_[0]->as_text eq "[link]";
        });
        print $after, ":\t", $link->attr('href'), "\n";
        my $pid = fork();
        unless(defined $pid) {
            die "Failed to fork\n";
        }
        unless($pid) {
            exec('getimage', $link->attr('href'));
        }
        while(wait() != -1) {};
        
        $desc->delete;
    }

    if($after eq $last_after) {
        last;
    }
    $page = $url . "?after=t3_" . $after;
    $last_after = $after;
}

ReadMode 0;

exit 0;
